Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ on:
     branches: [ master ]
 
 jobs:
-  build:
+  build:    
     runs-on: ubuntu-latest
 
     strategy:
@@ -25,14 +25,20 @@ jobs:
     - name: Check out code    
       uses: actions/checkout@v2
       
-    - name: Set up JDK ${{ matrix.java }}
+    - name: Set up Java ${{ matrix.java }}
       uses: actions/setup-java@v2
       with:
         java-version: ${{ matrix.java }}
         distribution: 'adopt'
         
-    - name: Build with Maven
+    - name: Build on Java ${{ matrix.java }}
       run: |
         mvn -B package --file pom.xml || echo "Build failed"
         cat snf4j-core/target/surefire-reports/*.txt
         cat snf4j-core-slf4j/target/surefire-reports/*.txt
+        
+    - name: Upload coverage report
+      if: matrix.java == 8
+      run: |
+        mvn cobertura:cobertura || echo "Code coverage failed"
+        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
